#pragma config(Motor,  port1,           wrist,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           driveBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveBackRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "settings.h"
#include "robotControl.c"

/* !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * IF YOU ARE NOT A TEAM PROGRAMMER:
 * DO NOT MODIFY CODE BELOW THIS LINE!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */



task main() {
	while (true) {

		driveControl();
		wristControl();
		armControl();

	}
}
