#pragma config(Motor,  port1,           wrist,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           arm3,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveBackRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "settings.h"
#include "robotControl.c"

task main() {

	while (true) {

		if (vexRT[Btn5D] == 1) {

			setDrive(0, -100, 0);
			wait1Msec(1000);
			halt();
			wait1Msec(2000);
			setWrist(MOTOR_MAX);
			wait1Msec(1250);
			halt();
			wait1Msec(2000);
			setArm(negate(MOTOR_MAX));
			wait1Msec(1500);
			halt();
		}

	}

}
