#pragma config(Motor,  port1,           wrist,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arm3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           driveBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveBackRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*
 *!! IF YOU ARE NOT A TEAM PROGRAMMER: !!*
 *!!     DO NOT MODIFY CODE BELOW!     !!*
 *!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/




// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code
#include "Vex_Competition_Includes.c"

// Constants
#include "settings.h"

// Functions for robot control
#include "robotControl.c"

// DISABLED #include "JoystickDriver.c"

void pre_auton()
{

  bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = true;

  halt();

}

task autonomous()
{

	setWrist(MOTOR_MAX);
	setArm(negate(MOTOR_MAX));

	wait1Msec(1000);

	setWrist(MOTOR_OFF_COAST);

	wait1Msec(5500);

	halt();

}

task usercontrol()
{
  while (true)
  {
  	wristControl();
  	driveControl();
    armControl();
  }
}
