#pragma config(Motor,  port1,           mantisLeft,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           arm3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           arm4,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveBackRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           driveFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveFrontRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mantisRight,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*
 *!! IF YOU ARE NOT A TEAM PROGRAMMER: !!*
 *!!     DO NOT MODIFY CODE BELOW!     !!*
 *!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/




// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code
#include "Vex_Competition_Includes.c"

// Import constants and user settings
#include "constants.h"
#include "settings.h"

// Import robot control library
#include "robotControl.c"

// Import autons
#include "autons.c"

// DISABLED #include "JoystickDriver.c"

void pre_auton() {

	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = true;

	halt();

}

task autonomous() {

	//autonRun(AUTON_MODE);
	autonFence();

}

task usercontrol() {

	killSwitchState = false;

	while (true) {
		if (!killSwitch()) {
			autonOverrideDetection();
			mantisControl();
			driveControl();
			armControl();
		} else {
			halt();
		}
	}
}
